### ISSUE TITLE
`update` fails for TestFlight

### ISSUE THREAD

**Issue by jerryc127** [mas-cli/mas#1105]
### Configuration

```text
mas ▁▁▁▁ 4.1.0
arch ▁▁▁ x86_64
from ▁▁▁ homebrew/core/mas
origin ▁ https://github.com/mas-cli/mas.git
rev ▁▁▁▁ 4fa8f4c1f5f2ae7e9a554451621d054bba0c7057
swift ▁▁ 6.0.3 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
driver ▁ 1.115.1
region ▁ HK
macos ▁▁ 15.7.2 (24G325)
mac ▁▁▁▁ iMac20,1
cpu ▁▁▁▁ Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
```

### Bug description

```
❯ mas upgrade
Error: Failed to install TestFlight (4.1.0) from /var/folders/5b/2qwrskzx03db7rfxhtzr49mm0000gn/T/TemporaryItems/NSIRD_mas_popiUQ/899247664-pxs7575530779163193042.pkg
Exit status: 1

Standard output:
installer: Package name is TestFlight
installer: Upgrading at base path /
installer: The upgrade failed. (「安裝程式」遇到導致安裝失敗的錯誤。請聯絡軟件製造商來尋求協助。 將檔案移到最後的目標時發生無法預期的錯誤。)

Standard error:
Dec 11 21:28:41  installer[6180] <Debug>: Product archive /var/folders/5b/2qwrskzx03db7rfxhtzr49mm0000gn/T/TemporaryItems/NSIRD_mas_popiUQ/899247664-pxs7575530779163193042.pkg trustLevel=401
Dec 11 21:28:41  installer[6180] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
Dec 11 21:28:41  installer[6180] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/var/folders/5b/2qwrskzx03db7rfxhtzr49mm0000gn/T/TemporaryItems/NSIRD_mas_popiUQ/899247664-pxs7575530779163193042.pkg#TestFlight.pkg
Dec 11 21:28:41  installer[6180] <Info>: Set authorization level to root for session
Dec 11 21:28:41  installer[6180] <Info>: Authorization is being checked, waiting until authorization arrives.
Dec 11 21:28:41  installer[6180] <Info>: Administrator authorization granted.
Dec 11 21:28:41  installer[6180] <Info>: Packages have been authorized for installation.
Dec 11 21:28:41  installer[6180] <Debug>: Will use PK session
Dec 11 21:28:41  installer[6180] <Debug>: Using authorization level of root for IFPKInstallElement
Dec 11 21:28:41  installer[6180] <Info>: Starting installation:
Dec 11 21:28:41  installer[6180] <Notice>: Configuring volume "Macintosh HD"
Dec 11 21:28:41  installer[6180] <Info>: Preparing disk for local booted install.
Dec 11 21:28:41  installer[6180] <Notice>: Free space on "Macintosh HD": 805.48 GB (805483941888 bytes).
Dec 11 21:28:41  installer[6180] <Notice>: Create temporary directory "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T//Install.6180XRUFeR"
Dec 11 21:28:41  installer[6180] <Notice>: IFPKInstallElement (1 packages)
Dec 11 21:28:41  installer[6180] <Info>: Current Path: /usr/sbin/installer
Dec 11 21:28:41  installer[6180] <Notice>: PackageKit: Enqueuing install with framework-specified quality of service (utility)
Dec 11 21:28:43  installer[6180] <Debug>: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=120 "將檔案移到最後的目標時發生無法預期的錯誤。" UserInfo={NSUnderlyingError=0x60000336df50 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}, NSLocalizedDescription=將檔案移到最後的目標時發生無法預期的錯誤。, arguments=(
	    "-f",
	    "-s",
	    "/Library/InstallerSandboxes/.PKInstallSandboxManager/1CBA2A85-EFE8-4396-9129-7B0BFA628316.activeSandbox/Root",
	    "/"
	)}
Dec 11 21:28:43  installer[6180] <Error>: Install failed: 「安裝程式」遇到導致安裝失敗的錯誤。請聯絡軟件製造商來尋求協助。
```

### Steps to reproduce

mas upgrade

**Comment by rgoldberg** [comment]
Have you been able to update or install any other apps using mas 4.1.0?

Have any others failed?

Thanks for any additional info.

**Comment by jerryc127** [comment]
All other apps update and install completely fine with mas 4.1.0.
The only one that failed for me today was TestFlight.

**Comment by rgoldberg** [comment]
Thanks for the info. Hopefully, I'll look into this later today.

I can't promise that I'll find any solutions anytime soon, as the whole installd workaround is a massive kludge.

Have you tried installing test flight via mas a second time?

If you haven't yet updated your TestFlight, can you copy the TestFlight app folder somewhere, so you can downgrade versions so you can update TestFlight multiple times to help with diagnostics?

If you have already successfully updated TestFlight, how did you do it? Via App Store, mas, etc.?

**Comment by jerryc127** [comment]
```
❯ mas outdated
899247664  TestFlight  (4.0.1 -> 4.1.0)
❯ mas upgrade
Password:
```

Update to the latest version, check outdated and find TestFlight, but mas upgrade shows blank

**Comment by rgoldberg** [comment]
Since you're using Homebrew Core's x86_64 binary, it sounds like you're experiencing the problem mentioned & solved in [this comment](https://github.com/mas-cli/mas/issues/1144#issuecomment-3677599889).

Please follow the instructions in the comment to remove the Homebrew Core formula & to install from the mas custom tap, then let me know if all works.

**Comment by jerryc127** [comment]
> Since you're using Homebrew Core's x86_64 binary, it sounds like you're experiencing the problem mentioned & solved in [this comment](https://github.com/mas-cli/mas/issues/1144#issuecomment-3677599889).
> 
> Please follow the instructions in the comment to remove the Homebrew Core formula & to install from the mas custom tap, then let me know if all works.

```
Last login: Sun Dec 21 01:55:14 on console
❯ brew uninstall --force mas
Uninstalling mas... (9 files, 3.6MB)
❯ sudo trash /usr/local/opt/mas /usr/local/bin/mas
Password:
2025-12-21 12:14:47.234 trash[1365:13237] # Error attempting to move /usr/local/opt/mas to the trash folder, Error Domain=NSCocoaErrorDomain Code=4 "The file “mas” doesn’t exist." UserInfo={NSURL=file:///usr/local/opt/mas, NSUserStringVariant=Trash, NSUnderlyingError=0x6000007fd260 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
2025-12-21 12:14:47.235 trash[1365:13237] # Error attempting to move /usr/local/bin/mas to the trash folder, Error Domain=NSCocoaErrorDomain Code=4 "The file “mas” doesn’t exist." UserInfo={NSURL=file:///usr/local/bin/mas, NSUserStringVariant=Trash, NSUnderlyingError=0x6000007f82a0 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
❯ which mas
mas not found
❯ mas
zsh: command not found: mas
❯ brew install mas-cli/tap/mas
==> Auto-updating Homebrew...
Adjust how often this is run with `$HOMEBREW_AUTO_UPDATE_SECS` or disable with
`$HOMEBREW_NO_AUTO_UPDATE=1`. Hide these hints with `$HOMEBREW_NO_ENV_HINTS=1` (see `man brew`).
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
octodns: Tools for managing DNS across multiple providers
vacuum: World's fastest OpenAPI & Swagger linter
wifitui: Fast featureful friendly wifi terminal UI

You have 1 outdated formula installed.

==> Tapping mas-cli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/mas-cli/homebrew-tap'...
remote: Enumerating objects: 446, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 446 (delta 129), reused 94 (delta 86), pack-reused 286 (from 3)
Receiving objects: 100% (446/446), 81.00 KiB | 2.19 MiB/s, done.
Resolving deltas: 100% (221/221), done.
Tapped 1 formula (19 files, 109.9KB).
==> Fetching downloads for: mas
✔︎ Bottle mas (4.1.1)                                                   [Downloaded  972.8KB/972.8KB]
==> Installing mas from mas-cli/tap
==> Pouring mas-4.1.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/mas/4.1.1: 9 files, 3.6MB
==> Running `brew cleanup mas`...
Disable this behaviour by setting `HOMEBREW_NO_INSTALL_CLEANUP=1`.
Hide these hints with `HOMEBREW_NO_ENV_HINTS=1` (see `man brew`).
❯ mas
OVERVIEW: Mac App Store command-line interface

USAGE: mas <subcommand>

OPTIONS:
  --version               Show the version.
  -h, --help              Show help information.

SUBCOMMANDS:
  account                 Output the Apple Account signed in to the App Store
  config                  Output mas config & related system info
  get, purchase           Get & install free apps from the App Store
  home                    Open App Store app pages in the default web browser
  install                 Install previously gotten apps from the App Store
  list                    List all apps installed from the App Store
  lookup, info            Output app information from the App Store
  lucky                   Install the first app returned from searching the App Store
  open                    Open app page in 'App Store.app'
  outdated                List pending app updates from the App Store
  region                  Output the assumed region of the App Store
  reset                   Reset App Store processes & clear cached App Store downloads
  search                  Search for apps in the App Store
  seller, vendor          Open apps' seller pages in the default web browser
  signin                  Sign in to an Apple Account in the App Store
  signout                 Sign out of the Apple Account currently signed in to the App Store
  uninstall               Uninstall apps installed from the App Store
  update, upgrade         Update outdated apps installed from the App Store
  version                 Output version number

  See 'mas help <subcommand>' for detailed help.
❯ mas outdated
899247664  TestFlight  (4.0.1 -> 4.1.0)
❯ mas upgrade
Password:
❯ mas upgrade 899247664

```

```
mas ▁▁▁▁ 4.1.1
slice ▁▁ x86_64
slices ▁ x86_64
dist ▁▁▁ mas-cli/tap/mas
origin ▁ https://github.com/mas-cli/mas.git
rev ▁▁▁▁ dac9fc222fe4c9a3a14a073f8ecbf93279568a74
swift ▁▁ 6.1.2 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
driver ▁ 1.120.5
store ▁▁ HK
region ▁ HK
macos ▁▁ 15.7.3 (24G419)
mac ▁▁▁▁ iMac20,1
cpu ▁▁▁▁ Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
arch ▁▁▁ x86_64
```

check outdated and find TestFlight, but mas upgrade still shows blank

**Comment by rgoldberg** [comment]
@jerryc127 Thanks for the info.

## TL;DR

Can you uninstall existing mas versions from your Mac:

```shell
brew uninstall --force mas
sudo trash /usr/local/opt/mas /usr/local/bin/mas
which mas
```

Then install mas 4.1.1 for x86_64 using the [GitHub Releases pkg installer](https://github.com/mas-cli/mas/releases/download/v4.1.1/mas-4.1.1-x86_64.pkg), then try again to update TestFlight, then report the results?

The pkg installer built mas 4.1.1 for x86_64 using Xcode 26 on macOS 26 on arm64; the mas custom tap built using Xcode 16.4 on macOS 15 on x86_64 (if necessary, this can be updated to Xcode 26, and to macOS 26 on arm64, it will just take extra work); Homebrew Core built using Xcode 16.2 on macOS 14 on x86_64 (this cannot be changed).

## Details

I was able to update TestFlight from 4.0.1 to 4.1.0 using Homebrew Core mas 4.1.1 on macOS 26 on arm64.

Did `mas upgrade 899247664` return or hang? If it returned, can you tell me the exit status? (`mas upgrade 899247664; echo $?`)

Other users experienced a hang installing Xcode on macOS 15.7.2 & 15.7.3 (see #1102); so maybe the issue is for Apple dev apps on macOS 15.7.x.

Using the custom Homebrew tap mas fixed a silent failure for another user, but it seems that's not your problem. See https://github.com/mas-cli/mas/issues/1144#issuecomment-3678425942.

Their problem was for all apps (they didn't specifically mention TestFlight) using Homebrew Core mas 4.1.1 on macOS 15.7.3. Their problem probably occurred only for Homebrew Core mas 4.1.1, for macOS 15.7.3, or for the pair thereof.

Your problem occurred only for TestFlight, not other apps, right? #1109 was erroneously considered a duplicate of this issue, so the solution for that issue closed this issue.

The best next step is to perform the steps in the TL;DR section above.

**Comment by jerryc127** [comment]
> Did mas upgrade 899247664 return or hang? If it returned, can you tell me the exit status? (mas upgrade 899247664; echo $?)

```
❯ mas upgrade 899247664; echo $?
Password:
1
```

> Then install mas 4.1.1 for x86_64 using the [GitHub Releases pkg installer](https://github.com/mas-cli/mas/releases/download/v4.1.1/mas-4.1.1-x86_64.pkg), then try again to update TestFlight, then report the results?

it works

```
❯ mas upgrade
==> Downloading TestFlight (4.1.0)
==> Downloaded TestFlight (4.1.0)
==> Installing TestFlight (4.1.0)
==> Installed TestFlight (4.1.0)
❯ mas config
mas ▁▁▁▁ 4.1.1
slice ▁▁ x86_64
slices ▁ x86_64
dist ▁▁▁ package
origin ▁ https://github.com/mas-cli/mas
rev ▁▁▁▁ dac9fc222fe4c9a3a14a073f8ecbf93279568a74
swift ▁▁ 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
driver ▁ 1.127.14.1
store ▁▁ HK
region ▁ HK
macos ▁▁ 15.7.3 (24G419)
mac ▁▁▁▁ iMac20,1
cpu ▁▁▁▁ Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
arch ▁▁▁ x86_64

```

**Comment by rgoldberg** [comment]
Thanks for the info.

The solution will be to require Xcode 26 to build for all distribution channels, macOS versions, and architectures.

That causes some knock-on effects with Homebrew that I am sorting out with advisors.

I'll leave this open until 5.0.0 is released with the requisite build changes.
