### ISSUE TITLE
🐛 [BUG] `mas outdated` gives incorrect information

### ISSUE THREAD

**Issue by JimDabell** [mas-cli/mas#290]
## Your Environment

- `mas version`: 1.7.0
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.15.5 (19F101)

### mas Install Method

- [x] `brew install mas` (homebrew-core)

## Describe the Bug

When I run `mas outdated`, it reports the following:

> `1449412482 Reeder 4 (4.2.5 -> 4.1.4)`

v4.2.5 is the latest version in the Mac App Store, and I have it installed.  v4.1.4 was released nine months ago.

When I visit the Reeder 4 page in the Mac App Store GUI application, I see that it is installed and the blue button says "OPEN".  When I open the Reeder application and check the version info there, it says I am running v4.2.5.

When I run `mas upgrade`, it tells me it will install v4.1.4, then downloads v4.2.5 and reinstalls it.  Checking with the Mac App Store and the Reeder application shows that the latest version is still installed.

After I do this, `mas outdated` no longer shows it as being out of date.

**Comment by Loreno10** [comment]
I have a bit different issue, but the general problem is the same - `mas outdated` does not provide accurate information.
In my case, App Store how's that 3 apps can be updated. `mas outdated` does not show any outdated apps. Also `mas upgrade` does not do anything. I'm on Catalina

**Comment by ppo** [comment]
Similar problem. App Store shows a new version in "Upcoming Automatic Updates" that doesn't appear with `mas outdated|upgrade`.

**Comment by aaronk1** [comment]
same 👍

**Comment by Blaisorblade** [comment]
Same 👍 , mas does not show this iMovie update (and I think it didn't show the previous one either).

- `mas version`: 1.7.0
- macOS version (`system_profiler SPSoftwareDataType -detailLevel mini`): 10.15.6 (19G2021)

### mas Install Method

- [x] `brew install mas` (homebrew-core)

```
$ mas outdated
$ mas upgrade
Everything is up-to-date
$ mas list
408981381 iPhoto (9.6.1)
406056744 Evernote (7.14)
682658836 GarageBand (10.3.5)
408981434 iMovie (10.1.14)
1444383602 GoodNotes (5.4.42)
409201541 Pages (10.1)
409183694 Keynote (10.1)
497799835 Xcode (11.6)
441258766 Magnet (2.4.6)
425424353 The Unarchiver (4.2.2)
409203825 Numbers (10.1)
```

But:
![image](https://user-images.githubusercontent.com/289960/91231633-e208e600-e72d-11ea-8891-ad6884de30c0.png)

**Comment by andrewcrook** [comment]
Mas: 1.7.0
OS: System Version: macOS 10.15.6 (19G2021)

Still having issues has never really worked properly with Catalina. 
I hope Big Sur works.

**example Goodnotes 5.5.6 released on 09/09/2020**

<img width="244" alt="image" src="https://user-images.githubusercontent.com/803618/92609656-bb5eb980-f2ae-11ea-8fef-2a3576c9bed8.png">

<img width="295" alt="image" src="https://user-images.githubusercontent.com/803618/92609737-d29da700-f2ae-11ea-8e41-681646b3fb77.png">

<img width="467" alt="Screenshot 2020-09-09 at 15 09 48" src="https://user-images.githubusercontent.com/803618/92609512-8f433880-f2ae-11ea-8286-72fdb14f5717.png">

App Store 

<img width="741" alt="image" src="https://user-images.githubusercontent.com/803618/92609867-f365fc80-f2ae-11ea-87da-d25aa84139a5.png">

Macupdater.org 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/803618/92610017-23ad9b00-f2af-11ea-9707-0b15f9a35263.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/803618/92609980-17c1d900-f2af-11ea-9eff-56a40a043662.png">

**Comment by garrettoreilly** [comment]
More conversation about this in #252.

**Comment by charlietomo** [comment]
I'm also having this issue, i.e. mas does not detect when upgrades are available.

Having read multiple other threads about this, it seems to be an ongoing issue that has not been resolved. I appreciate this is open source software and it has been helpful for me for setting up a new laptop.

If I complete the update in the Apple GUI for App Store then the update works, and a `brew list` shows the updated version. Hopefully this may get fixed in the future, but in the meantime updating via GUI is not a big issue for me.

**Comment by phatblat** [comment]
Should be fixed now in [1.8.1](https://github.com/mas-cli/mas/releases/tag/v1.8.1). @JimDabell can you confirm?

**Comment by pro-sumer** [comment]
I still get incorrect information with 1.8.1:

```
❯ mas outdated
1504761986 San Fransymbols (3.0 -> 2.2.2)
1026349850 Copied (4.0.1 -> 4.0.4)
325206381 Flame (2.6.0 -> 2.6.1)
288545208 Instapaper (8.0.1 -> 8.0)
1469995354 Broadcasts (1.3.8 -> 1.3.6)
615538630 Geofency (6.9 -> 6.9.1)
```

**Comment by JimDabell** [comment]
I still see incorrect information. When I open the Mac App Store, I see three applications that need updating. When I run `mas outdated`, four applications are listed. The additional one is:

`405399194 Kindle (1.30.0 -> 1.30)`

When I visit the Mac App Store page for that application, it shows that 1.30 is the latest version, released four months ago, and that I have it installed. When I run `mas upgrade`, it downloads and installs the latest version of Kindle. When I run `mas outdated` again, I see the same output as before, with it telling me I need to upgrade from `1.30.0` to `1.30`.

**Comment by pro-sumer** [comment]
> I still get incorrect information with 1.8.1

Looks like the version number on the right side of the arrow is of the iOS App instead of the macOS App?

**Comment by lonelykid** [comment]
@pro-sumer I can confirm `mas info 1249901692` shows the IOS version of ScanScan. I believe some other Apps are also in this situation. `mas info 571213070` DaVinci Resolve 17.1 is a little different. The version fetched is the same as in AppStore, but the version installed seems to be 17.1.0. I would suggest 
1. Using `https://apps.apple.com/app/id1249901692` HTML to get the version number.
2. Only display larger value new version.

**Comment by andrewcrook** [comment]
> 
> `405399194 Kindle (1.30.0 -> 1.30)`
> 

I think this one can be fixed using hack to get around it. Because they are basically the same version.

**Comment by brandonkal** [comment]
Along these same lines, it lists apps that require Big Sur when running Catalina.

**Comment by chris-araman** [comment]
The remaining discrepancies in `outdated` should be resolved by #346.

> Along these same lines, it lists apps that require Big Sur when running Catalina.

@brandonkal, would you be able to open a new issue with details on this?
